CREATE OR REPLACE PROCEDURE bitwarden.User_Create
(
    _Id UUID,
    _Name VARCHAR(50),
    _Email VARCHAR(50),
    _EmailVerified BIT,
    _MasterPassword VARCHAR(300),
    _MasterPasswordHint VARCHAR(50),
    _Culture VARCHAR(10),
    _SecurityStamp VARCHAR(50),
    _TwoFactorProviders TEXT,
    _TwoFactorRecoveryCode VARCHAR(32),
    _EquivalentDomains TEXT,
    _ExcludedGlobalEquivalentDomains TEXT,
    _AccountRevisionDate TIMESTAMPTZ,
    _Key TEXT,
    _PublicKey TEXT,
    _PrivateKey TEXT,
    _Premium BIT,
    _PremiumExpirationDate TIMESTAMPTZ,
    _RenewalReminderDate TIMESTAMPTZ,
    _Storage BIGINT,
    _MaxStorageGb SMALLINT,
    _Gateway SMALLINT,
    _GatewayCustomerId VARCHAR(50),
    _GatewaySubscriptionId VARCHAR(50),
    _LicenseKey VARCHAR(100),
    _Kdf SMALLINT,
    _KdfIterations INT,
    _CreationDate TIMESTAMPTZ,
    _RevisionDate TIMESTAMPTZ
)
LANGUAGE 'plpgsql'
AS
$$
BEGIN
    INSERT INTO bitwarden.User
    (
        Id,
        Name,
        Email,
        EmailVerified,
        MasterPassword,
        MasterPasswordHint,
        Culture,
        SecurityStamp,
        TwoFactorProviders,
        TwoFactorRecoveryCode,
        EquivalentDomains,
        ExcludedGlobalEquivalentDomains,
        AccountRevisionDate,
        Key,
        PublicKey,
        PrivateKey,
        Premium,
        PremiumExpirationDate,
        RenewalReminderDate,
        Storage,
        MaxStorageGb,
        Gateway,
        GatewayCustomerId,
        GatewaySubscriptionId,
        LicenseKey,
        Kdf,
        KdfIterations,
        CreationDate,
        RevisionDate
    )
    VALUES
    (
        _Id,
        _Name,
        _Email,
        _EmailVerified,
        _MasterPassword,
        _MasterPasswordHint,
        _Culture,
        _SecurityStamp,
        _TwoFactorProviders,
        _TwoFactorRecoveryCode,
        _EquivalentDomains,
        _ExcludedGlobalEquivalentDomains,
        _AccountRevisionDate,
        _Key,
        _PublicKey,
        _PrivateKey,
        _Premium,
        _PremiumExpirationDate,
        _RenewalReminderDate,
        _Storage,
        _MaxStorageGb,
        _Gateway,
        _GatewayCustomerId,
        _GatewaySubscriptionId,
        _LicenseKey,
        _Kdf,
        _KdfIterations,
        _CreationDate,
        _RevisionDate
    );
END
$$