using Bit.Core.Billing.Enums;
using Bit.Core.Exceptions;
using Bit.Core.Models.StaticStore;

namespace Bit.Core.Billing.Pricing;

internal sealed class LocalPricingClient : IPricingClient
{
    private static readonly IReadOnlyList<Plan> _localPlans =
    [
        LocalPlan.CreateFreePlan(),
        LocalPlan.CreateFamilies2019Plan(),
        LocalPlan.CreateFamilies2025Plan(),
        LocalPlan.CreateFamiliesPlan(),
        LocalPlan.CreateTeams2019Plan(isAnnual: true),
        LocalPlan.CreateTeams2019Plan(isAnnual: false),
        LocalPlan.CreateTeams2020Plan(isAnnual: true),
        LocalPlan.CreateTeams2020Plan(isAnnual: false),
        LocalPlan.CreateTeams2023Plan(isAnnual: true),
        LocalPlan.CreateTeams2023Plan(isAnnual: false),
        LocalPlan.CreateTeamsPlan(isAnnual: true),
        LocalPlan.CreateTeamsPlan(isAnnual: false),
        LocalPlan.CreateTeamsStarterPlan(),
        LocalPlan.CreateTeamsStarter2023Plan(),
        LocalPlan.CreateEnterprise2019Plan(isAnnual: true),
        LocalPlan.CreateEnterprise2019Plan(isAnnual: false),
        LocalPlan.CreateEnterprise2020Plan(isAnnual: true),
        LocalPlan.CreateEnterprise2020Plan(isAnnual: false),
        LocalPlan.CreateEnterprise2023Plan(isAnnual: true),
        LocalPlan.CreateEnterprise2023Plan(isAnnual: false),
        LocalPlan.CreateEnterprisePlan(isAnnual: true),
        LocalPlan.CreateEnterprisePlan(isAnnual: false),
    ];

    private static readonly IReadOnlyList<Premium.Plan> _localPremiumPlans =
    [
        new Premium.Plan
        {
            Name = "Premium",
            LegacyYear = null,
            Available = true,
            Seat = new Premium.Purchasable
            {
                StripePriceId = "premium-annually-2026",
                Price = 19.80M,
            },
            Storage = new Premium.Purchasable
            {
                Provided = 5,
                StripePriceId = "personal-storage-gb-annually",
                Price = 4M,
            },
        },
        new Premium.Plan
        {
            Name = "Premium (Annually) 2025",
            LegacyYear = 2025,
            Available = false,
            Seat = new Premium.Purchasable
            {
                StripePriceId = "premium-annually",
                Price = 10M,
            },
            Storage = new Premium.Purchasable
            {
                Provided = 5,
                StripePriceId = "personal-storage-gb-annually",
                Price = 4M,
            },
        },
    ];

    public async Task<Premium.Plan> GetAvailablePremiumPlan()
    {
        var premiumPlans = await ListPremiumPlans();
        var availablePlan = premiumPlans.FirstOrDefault(premiumPlan => premiumPlan.Available);
        return availablePlan ?? throw new NotFoundException("Could not find available premium plan");
    }

    public Task<Plan?> GetPlan(PlanType planType) =>
        Task.FromResult(_localPlans.FirstOrDefault(plan => plan.Type == planType));

    public async Task<Plan> GetPlanOrThrow(PlanType planType) =>
        await GetPlan(planType) ?? throw new NotFoundException($"Could not find plan for type {planType}");

    public Task<List<Plan>> ListPlans() => Task.FromResult(_localPlans.ToList());

    public Task<List<Premium.Plan>> ListPremiumPlans() => Task.FromResult(_localPremiumPlans.ToList());

    private record LocalPlan : Plan
    {
        public static LocalPlan CreateFreePlan() => new()
        {
            Type = PlanType.Free,
            ProductTier = ProductTierType.Free,
            Name = "Free",
            IsAnnual = false,
            NameLocalizationKey = "planNameFree",
            DescriptionLocalizationKey = "planDescFree",
            CanBeUsedByBusiness = false,
            TrialPeriodDays = null,
            HasSelfHost = false,
            HasPolicies = false,
            HasGroups = false,
            HasDirectory = false,
            HasEvents = false,
            HasTotp = false,
            Has2fa = false,
            HasApi = false,
            HasSso = false,
            HasOrganizationDomains = false,
            HasKeyConnector = false,
            HasScim = false,
            HasResetPassword = false,
            UsersGetPremium = false,
            HasCustomPermissions = false,
            HasMyItems = false,
            HasInviteLinks = false,
            UpgradeSortOrder = -1,
            DisplaySortOrder = -1,
            LegacyYear = null,
            Disabled = false,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = null,
                StripeSeatPlanId = null,
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 0,
                SeatPrice = 0,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = false,
                HasAdditionalSeatsOption = false,
                MaxAdditionalSeats = null,
                BaseSeats = 2,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = 2,
                BaseStorageGb = 0,
                HasAdditionalStorageOption = false,
                AdditionalStoragePricePerGb = 0,
                StripeStoragePlanId = null,
                MaxAdditionalStorage = null,
                MaxCollections = 2,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 3,
                AllowServiceAccountsAutoscale = false,
                StripeServiceAccountPlanId = null,
                AdditionalPricePerServiceAccount = 0,
                BaseServiceAccount = 3,
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = false,
                StripeSeatPlanId = null,
                HasAdditionalSeatsOption = false,
                BasePrice = 0,
                SeatPrice = 0,
                BaseSeats = 2,
                MaxSeats = 2,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = false,
                MaxProjects = 3,
            },
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateFamilies2019Plan() => new()
        {
            Type = PlanType.FamiliesAnnually2019,
            ProductTier = ProductTierType.Families,
            Name = "Families 2019",
            IsAnnual = true,
            NameLocalizationKey = "planNameFamilies",
            DescriptionLocalizationKey = "planDescFamilies",
            CanBeUsedByBusiness = false,
            TrialPeriodDays = 7,
            HasSelfHost = true,
            HasPolicies = false,
            HasGroups = false,
            HasDirectory = false,
            HasEvents = false,
            HasTotp = true,
            Has2fa = false,
            HasApi = false,
            HasSso = false,
            HasOrganizationDomains = false,
            HasKeyConnector = false,
            HasScim = false,
            HasResetPassword = false,
            UsersGetPremium = false,
            HasCustomPermissions = false,
            HasMyItems = false,
            HasInviteLinks = false,
            UpgradeSortOrder = 1,
            DisplaySortOrder = 1,
            LegacyYear = 2019,
            Disabled = true,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = "personal-org-annually",
                StripeSeatPlanId = null,
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 12,
                SeatPrice = 0,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = false,
                HasAdditionalSeatsOption = false,
                MaxAdditionalSeats = null,
                BaseSeats = 5,
                HasPremiumAccessOption = true,
                StripePremiumAccessPlanId = "personal-org-premium-access-annually",
                PremiumAccessOptionPrice = 40,
                MaxSeats = 5,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = 4,
                StripeStoragePlanId = "personal-storage-gb-annually",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = null,
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateFamilies2025Plan() => new()
        {
            Type = PlanType.FamiliesAnnually2025,
            ProductTier = ProductTierType.Families,
            Name = "Families 2025",
            IsAnnual = true,
            NameLocalizationKey = "planNameFamilies",
            DescriptionLocalizationKey = "planDescFamilies",
            CanBeUsedByBusiness = false,
            TrialPeriodDays = 7,
            HasSelfHost = true,
            HasPolicies = false,
            HasGroups = false,
            HasDirectory = false,
            HasEvents = false,
            HasTotp = true,
            Has2fa = false,
            HasApi = false,
            HasSso = false,
            HasOrganizationDomains = false,
            HasKeyConnector = false,
            HasScim = false,
            HasResetPassword = false,
            UsersGetPremium = true,
            HasCustomPermissions = false,
            HasMyItems = false,
            HasInviteLinks = false,
            UpgradeSortOrder = 1,
            DisplaySortOrder = 1,
            LegacyYear = null,
            Disabled = false,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = "2020-families-org-annually",
                StripeSeatPlanId = null,
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 40,
                SeatPrice = 0,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = false,
                HasAdditionalSeatsOption = false,
                MaxAdditionalSeats = null,
                BaseSeats = 6,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = 6,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = 4,
                StripeStoragePlanId = "personal-storage-gb-annually",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = null,
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateFamiliesPlan() => new()
        {
            Type = PlanType.FamiliesAnnually,
            ProductTier = ProductTierType.Families,
            Name = "Families",
            IsAnnual = true,
            NameLocalizationKey = "planNameFamilies",
            DescriptionLocalizationKey = "planDescFamilies",
            CanBeUsedByBusiness = false,
            TrialPeriodDays = 7,
            HasSelfHost = true,
            HasPolicies = false,
            HasGroups = false,
            HasDirectory = false,
            HasEvents = false,
            HasTotp = true,
            Has2fa = false,
            HasApi = false,
            HasSso = false,
            HasOrganizationDomains = false,
            HasKeyConnector = false,
            HasScim = false,
            HasResetPassword = false,
            UsersGetPremium = true,
            HasCustomPermissions = false,
            HasMyItems = false,
            HasInviteLinks = false,
            UpgradeSortOrder = 1,
            DisplaySortOrder = 1,
            LegacyYear = null,
            Disabled = false,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = "2026-families-annually",
                StripeSeatPlanId = null,
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 47.88M,
                SeatPrice = 0,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = false,
                HasAdditionalSeatsOption = false,
                MaxAdditionalSeats = null,
                BaseSeats = 6,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = 6,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = 4,
                StripeStoragePlanId = "personal-storage-gb-annually",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = null,
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateTeams2019Plan(bool isAnnual) => new()
        {
            Type = isAnnual ? PlanType.TeamsAnnually2019 : PlanType.TeamsMonthly2019,
            ProductTier = ProductTierType.Teams,
            Name = isAnnual ? "Teams (Annually) 2019" : "Teams (Monthly) 2019",
            IsAnnual = isAnnual,
            NameLocalizationKey = "planNameTeams",
            DescriptionLocalizationKey = "planDescTeams",
            CanBeUsedByBusiness = true,
            TrialPeriodDays = 7,
            HasSelfHost = false,
            HasPolicies = false,
            HasGroups = true,
            HasDirectory = true,
            HasEvents = true,
            HasTotp = true,
            Has2fa = true,
            HasApi = true,
            HasSso = false,
            HasOrganizationDomains = false,
            HasKeyConnector = false,
            HasScim = false,
            HasResetPassword = false,
            UsersGetPremium = true,
            HasCustomPermissions = false,
            HasMyItems = false,
            HasInviteLinks = false,
            UpgradeSortOrder = 3,
            DisplaySortOrder = 3,
            LegacyYear = 2019,
            Disabled = true,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = isAnnual ? "teams-org-annually" : "teams-org-monthly",
                StripeSeatPlanId = isAnnual ? "teams-org-seat-annually" : "teams-org-seat-monthly",
                StripeProviderPortalSeatPlanId = null,
                BasePrice = isAnnual ? 60 : 8,
                SeatPrice = isAnnual ? 24 : 2.5M,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = true,
                HasAdditionalSeatsOption = true,
                MaxAdditionalSeats = null,
                BaseSeats = 5,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = 5,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = isAnnual ? 4 : 0.5M,
                StripeStoragePlanId = isAnnual ? "storage-gb-annually" : "storage-gb-monthly",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 0,
                AllowServiceAccountsAutoscale = true,
                StripeServiceAccountPlanId = isAnnual ? "secrets-manager-service-account-annually" : "secrets-manager-service-account-monthly",
                AdditionalPricePerServiceAccount = isAnnual ? 6 : 0.5M,
                BaseServiceAccount = 50,
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = true,
                StripeSeatPlanId = isAnnual ? "secrets-manager-teams-seat-annually" : "secrets-manager-teams-seat-monthly",
                HasAdditionalSeatsOption = true,
                BasePrice = 0,
                SeatPrice = isAnnual ? 72 : 7,
                BaseSeats = 0,
                MaxSeats = 0,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = true,
                MaxProjects = 0,
            },
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateTeams2020Plan(bool isAnnual) => new()
        {
            Type = isAnnual ? PlanType.TeamsAnnually2020 : PlanType.TeamsMonthly2020,
            ProductTier = ProductTierType.Teams,
            Name = isAnnual ? "Teams (Annually) 2020" : "Teams (Monthly) 2020",
            IsAnnual = isAnnual,
            NameLocalizationKey = "planNameTeams",
            DescriptionLocalizationKey = "planDescTeams",
            CanBeUsedByBusiness = true,
            TrialPeriodDays = 7,
            HasSelfHost = false,
            HasPolicies = false,
            HasGroups = true,
            HasDirectory = true,
            HasEvents = true,
            HasTotp = true,
            Has2fa = true,
            HasApi = true,
            HasSso = false,
            HasOrganizationDomains = false,
            HasKeyConnector = false,
            HasScim = false,
            HasResetPassword = false,
            UsersGetPremium = true,
            HasCustomPermissions = false,
            HasMyItems = false,
            HasInviteLinks = false,
            UpgradeSortOrder = 3,
            DisplaySortOrder = 3,
            LegacyYear = 2020,
            Disabled = true,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = null,
                StripeSeatPlanId = isAnnual ? "2020-teams-org-seat-annually" : "2020-teams-org-seat-monthly",
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 0,
                SeatPrice = isAnnual ? 36 : 4,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = true,
                HasAdditionalSeatsOption = true,
                MaxAdditionalSeats = null,
                BaseSeats = 0,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = null,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = isAnnual ? 4 : 0.5M,
                StripeStoragePlanId = isAnnual ? "storage-gb-annually" : "storage-gb-monthly",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 0,
                AllowServiceAccountsAutoscale = true,
                StripeServiceAccountPlanId = isAnnual ? "secrets-manager-service-account-annually" : "secrets-manager-service-account-monthly",
                AdditionalPricePerServiceAccount = isAnnual ? 6 : 0.5M,
                BaseServiceAccount = 50,
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = true,
                StripeSeatPlanId = isAnnual ? "secrets-manager-teams-seat-annually" : "secrets-manager-teams-seat-monthly",
                HasAdditionalSeatsOption = true,
                BasePrice = 0,
                SeatPrice = isAnnual ? 72 : 7,
                BaseSeats = 0,
                MaxSeats = 0,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = true,
                MaxProjects = 0,
            },
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateTeams2023Plan(bool isAnnual) => new()
        {
            Type = isAnnual ? PlanType.TeamsAnnually2023 : PlanType.TeamsMonthly2023,
            ProductTier = ProductTierType.Teams,
            Name = isAnnual ? "Teams (Annually) 2023" : "Teams (Monthly) 2023",
            IsAnnual = isAnnual,
            NameLocalizationKey = "planNameTeams",
            DescriptionLocalizationKey = "planDescTeams",
            CanBeUsedByBusiness = true,
            TrialPeriodDays = 7,
            HasSelfHost = false,
            HasPolicies = false,
            HasGroups = true,
            HasDirectory = true,
            HasEvents = true,
            HasTotp = true,
            Has2fa = true,
            HasApi = true,
            HasSso = false,
            HasOrganizationDomains = false,
            HasKeyConnector = false,
            HasScim = false,
            HasResetPassword = false,
            UsersGetPremium = true,
            HasCustomPermissions = false,
            HasMyItems = false,
            HasInviteLinks = false,
            UpgradeSortOrder = 3,
            DisplaySortOrder = 3,
            LegacyYear = 2023,
            Disabled = true,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = null,
                StripeSeatPlanId = isAnnual ? "2023-teams-org-seat-annually" : "2023-teams-org-seat-monthly",
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 0,
                SeatPrice = isAnnual ? 48 : 5,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = true,
                HasAdditionalSeatsOption = true,
                MaxAdditionalSeats = null,
                BaseSeats = 0,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = null,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = isAnnual ? 4 : 0.5M,
                StripeStoragePlanId = isAnnual ? "storage-gb-annually" : "storage-gb-monthly",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 0,
                AllowServiceAccountsAutoscale = true,
                StripeServiceAccountPlanId = isAnnual ? "secrets-manager-service-account-annually" : "secrets-manager-service-account-monthly",
                AdditionalPricePerServiceAccount = isAnnual ? 6 : 0.5M,
                BaseServiceAccount = 50,
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = true,
                StripeSeatPlanId = isAnnual ? "secrets-manager-teams-seat-annually" : "secrets-manager-teams-seat-monthly",
                HasAdditionalSeatsOption = true,
                BasePrice = 0,
                SeatPrice = isAnnual ? 72 : 7,
                BaseSeats = 0,
                MaxSeats = 0,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = true,
                MaxProjects = 0,
            },
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateTeamsPlan(bool isAnnual) => new()
        {
            Type = isAnnual ? PlanType.TeamsAnnually : PlanType.TeamsMonthly,
            ProductTier = ProductTierType.Teams,
            Name = isAnnual ? "Teams (Annually)" : "Teams (Monthly)",
            IsAnnual = isAnnual,
            NameLocalizationKey = "planNameTeams",
            DescriptionLocalizationKey = "planDescTeams",
            CanBeUsedByBusiness = true,
            TrialPeriodDays = 7,
            HasSelfHost = false,
            HasPolicies = false,
            HasGroups = true,
            HasDirectory = true,
            HasEvents = true,
            HasTotp = true,
            Has2fa = true,
            HasApi = true,
            HasSso = false,
            HasOrganizationDomains = false,
            HasKeyConnector = false,
            HasScim = true,
            HasResetPassword = false,
            UsersGetPremium = true,
            HasCustomPermissions = false,
            HasMyItems = false,
            HasInviteLinks = false,
            UpgradeSortOrder = 3,
            DisplaySortOrder = 3,
            LegacyYear = null,
            Disabled = false,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = null,
                StripeSeatPlanId = isAnnual ? "2023-teams-org-seat-annually" : "2023-teams-org-seat-monthly",
                StripeProviderPortalSeatPlanId = isAnnual ? null : "password-manager-provider-portal-teams-monthly-2024",
                BasePrice = 0,
                SeatPrice = isAnnual ? 48 : 5,
                ProviderPortalSeatPrice = isAnnual ? 0 : 4,
                AllowSeatAutoscale = true,
                HasAdditionalSeatsOption = true,
                MaxAdditionalSeats = null,
                BaseSeats = 0,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = null,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = isAnnual ? 4 : 0.5M,
                StripeStoragePlanId = isAnnual ? "storage-gb-annually" : "storage-gb-monthly",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 0,
                AllowServiceAccountsAutoscale = true,
                StripeServiceAccountPlanId = isAnnual ? "secrets-manager-service-account-2024-annually" : "secrets-manager-service-account-2024-monthly",
                AdditionalPricePerServiceAccount = isAnnual ? 6 : 1,
                BaseServiceAccount = (short)(isAnnual ? 50 : 20),
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = true,
                StripeSeatPlanId = isAnnual ? "secrets-manager-teams-seat-annually" : "secrets-manager-teams-seat-monthly",
                HasAdditionalSeatsOption = true,
                BasePrice = 0,
                SeatPrice = isAnnual ? 72 : 7,
                BaseSeats = 0,
                MaxSeats = 0,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = true,
                MaxProjects = 0,
            },
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateTeamsStarterPlan() => new()
        {
            Type = PlanType.TeamsStarter,
            ProductTier = ProductTierType.TeamsStarter,
            Name = "Teams Starter",
            IsAnnual = false,
            NameLocalizationKey = "planNameTeamsStarter",
            DescriptionLocalizationKey = "planDescTeams",
            CanBeUsedByBusiness = true,
            TrialPeriodDays = 7,
            HasSelfHost = false,
            HasPolicies = false,
            HasGroups = true,
            HasDirectory = true,
            HasEvents = true,
            HasTotp = true,
            Has2fa = true,
            HasApi = true,
            HasSso = false,
            HasOrganizationDomains = false,
            HasKeyConnector = false,
            HasScim = true,
            HasResetPassword = false,
            UsersGetPremium = true,
            HasCustomPermissions = false,
            HasMyItems = false,
            HasInviteLinks = false,
            UpgradeSortOrder = 2,
            DisplaySortOrder = 2,
            LegacyYear = null,
            Disabled = true,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = "teams-org-starter",
                StripeSeatPlanId = null,
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 20,
                SeatPrice = 0,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = false,
                HasAdditionalSeatsOption = false,
                MaxAdditionalSeats = null,
                BaseSeats = 10,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = 10,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = 0.5M,
                StripeStoragePlanId = "storage-gb-monthly",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 0,
                AllowServiceAccountsAutoscale = true,
                StripeServiceAccountPlanId = "secrets-manager-service-account-2024-monthly",
                AdditionalPricePerServiceAccount = 1,
                BaseServiceAccount = 20,
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = true,
                StripeSeatPlanId = "secrets-manager-teams-seat-monthly",
                HasAdditionalSeatsOption = true,
                BasePrice = 0,
                SeatPrice = 7,
                BaseSeats = 0,
                MaxSeats = 0,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = true,
                MaxProjects = 0,
            },
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateTeamsStarter2023Plan() => new()
        {
            Type = PlanType.TeamsStarter2023,
            ProductTier = ProductTierType.TeamsStarter,
            Name = "Teams Starter 2023",
            IsAnnual = false,
            NameLocalizationKey = "planNameTeamsStarter",
            DescriptionLocalizationKey = "planDescTeams",
            CanBeUsedByBusiness = true,
            TrialPeriodDays = 7,
            HasSelfHost = false,
            HasPolicies = false,
            HasGroups = true,
            HasDirectory = true,
            HasEvents = true,
            HasTotp = true,
            Has2fa = true,
            HasApi = true,
            HasSso = false,
            HasOrganizationDomains = false,
            HasKeyConnector = false,
            HasScim = true,
            HasResetPassword = false,
            UsersGetPremium = true,
            HasCustomPermissions = false,
            HasMyItems = false,
            HasInviteLinks = false,
            UpgradeSortOrder = 2,
            DisplaySortOrder = 2,
            LegacyYear = 2023,
            Disabled = true,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = "teams-org-starter",
                StripeSeatPlanId = null,
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 20,
                SeatPrice = 0,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = false,
                HasAdditionalSeatsOption = false,
                MaxAdditionalSeats = null,
                BaseSeats = 10,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = 10,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = 0.5M,
                StripeStoragePlanId = "storage-gb-monthly",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 0,
                AllowServiceAccountsAutoscale = true,
                StripeServiceAccountPlanId = "secrets-manager-service-account-monthly",
                AdditionalPricePerServiceAccount = 0.5M,
                BaseServiceAccount = 50,
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = true,
                StripeSeatPlanId = "secrets-manager-teams-seat-monthly",
                HasAdditionalSeatsOption = true,
                BasePrice = 0,
                SeatPrice = 7,
                BaseSeats = 0,
                MaxSeats = 0,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = true,
                MaxProjects = 0,
            },
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateEnterprise2019Plan(bool isAnnual) => new()
        {
            Type = isAnnual ? PlanType.EnterpriseAnnually2019 : PlanType.EnterpriseMonthly2019,
            ProductTier = ProductTierType.Enterprise,
            Name = isAnnual ? "Enterprise (Annually) 2019" : "Enterprise (Monthly) 2019",
            IsAnnual = isAnnual,
            NameLocalizationKey = "planNameEnterprise",
            DescriptionLocalizationKey = "planDescEnterprise",
            CanBeUsedByBusiness = true,
            TrialPeriodDays = 7,
            HasSelfHost = true,
            HasPolicies = true,
            HasGroups = true,
            HasDirectory = true,
            HasEvents = true,
            HasTotp = true,
            Has2fa = true,
            HasApi = true,
            HasSso = true,
            HasOrganizationDomains = true,
            HasKeyConnector = true,
            HasScim = true,
            HasResetPassword = true,
            UsersGetPremium = true,
            HasCustomPermissions = true,
            HasMyItems = true,
            HasInviteLinks = true,
            UpgradeSortOrder = 4,
            DisplaySortOrder = 4,
            LegacyYear = 2019,
            Disabled = true,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = null,
                StripeSeatPlanId = isAnnual ? "enterprise-org-seat-annually" : "enterprise-org-seat-monthly",
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 0,
                SeatPrice = isAnnual ? 36 : 4M,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = true,
                HasAdditionalSeatsOption = true,
                MaxAdditionalSeats = null,
                BaseSeats = 0,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = null,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = isAnnual ? 4 : 0.5M,
                StripeStoragePlanId = isAnnual ? "storage-gb-annually" : "storage-gb-monthly",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 0,
                AllowServiceAccountsAutoscale = true,
                StripeServiceAccountPlanId = isAnnual ? "secrets-manager-service-account-annually" : "secrets-manager-service-account-monthly",
                AdditionalPricePerServiceAccount = isAnnual ? 6 : 0.5M,
                BaseServiceAccount = 200,
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = true,
                StripeSeatPlanId = isAnnual ? "secrets-manager-enterprise-seat-annually" : "secrets-manager-enterprise-seat-monthly",
                HasAdditionalSeatsOption = true,
                BasePrice = 0,
                SeatPrice = isAnnual ? 144 : 13,
                BaseSeats = 0,
                MaxSeats = 0,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = true,
                MaxProjects = 0,
            },
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateEnterprise2020Plan(bool isAnnual) => new()
        {
            Type = isAnnual ? PlanType.EnterpriseAnnually2020 : PlanType.EnterpriseMonthly2020,
            ProductTier = ProductTierType.Enterprise,
            Name = isAnnual ? "Enterprise (Annually) 2020" : "Enterprise (Monthly) 2020",
            IsAnnual = isAnnual,
            NameLocalizationKey = "planNameEnterprise",
            DescriptionLocalizationKey = "planDescEnterprise",
            CanBeUsedByBusiness = true,
            TrialPeriodDays = 7,
            HasSelfHost = true,
            HasPolicies = true,
            HasGroups = true,
            HasDirectory = true,
            HasEvents = true,
            HasTotp = true,
            Has2fa = true,
            HasApi = true,
            HasSso = true,
            HasOrganizationDomains = true,
            HasKeyConnector = true,
            HasScim = true,
            HasResetPassword = true,
            UsersGetPremium = true,
            HasCustomPermissions = true,
            HasMyItems = true,
            HasInviteLinks = true,
            UpgradeSortOrder = 4,
            DisplaySortOrder = 4,
            LegacyYear = 2020,
            Disabled = true,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = null,
                StripeSeatPlanId = isAnnual ? "2020-enterprise-org-seat-annually" : "2020-enterprise-seat-monthly",
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 0,
                SeatPrice = isAnnual ? 60 : 6,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = true,
                HasAdditionalSeatsOption = true,
                MaxAdditionalSeats = null,
                BaseSeats = 0,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = null,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = isAnnual ? 4 : 0.5M,
                StripeStoragePlanId = isAnnual ? "storage-gb-annually" : "storage-gb-monthly",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 0,
                AllowServiceAccountsAutoscale = true,
                StripeServiceAccountPlanId = isAnnual ? "secrets-manager-service-account-annually" : "secrets-manager-service-account-monthly",
                AdditionalPricePerServiceAccount = isAnnual ? 6 : 0.5M,
                BaseServiceAccount = 200,
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = true,
                StripeSeatPlanId = isAnnual ? "secrets-manager-enterprise-seat-annually" : "secrets-manager-enterprise-seat-monthly",
                HasAdditionalSeatsOption = true,
                BasePrice = 0,
                SeatPrice = isAnnual ? 144 : 13,
                BaseSeats = 0,
                MaxSeats = 0,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = true,
                MaxProjects = 0,
            },
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateEnterprise2023Plan(bool isAnnual) => new()
        {
            Type = isAnnual ? PlanType.EnterpriseAnnually2023 : PlanType.EnterpriseMonthly2023,
            ProductTier = ProductTierType.Enterprise,
            Name = isAnnual ? "Enterprise (Annually) 2023" : "Enterprise (Monthly) 2023",
            IsAnnual = isAnnual,
            NameLocalizationKey = "planNameEnterprise",
            DescriptionLocalizationKey = "planDescEnterprise",
            CanBeUsedByBusiness = true,
            TrialPeriodDays = 7,
            HasSelfHost = true,
            HasPolicies = true,
            HasGroups = true,
            HasDirectory = true,
            HasEvents = true,
            HasTotp = true,
            Has2fa = true,
            HasApi = true,
            HasSso = true,
            HasOrganizationDomains = true,
            HasKeyConnector = true,
            HasScim = true,
            HasResetPassword = true,
            UsersGetPremium = true,
            HasCustomPermissions = true,
            HasMyItems = true,
            HasInviteLinks = true,
            UpgradeSortOrder = 4,
            DisplaySortOrder = 4,
            LegacyYear = 2023,
            Disabled = true,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = null,
                StripeSeatPlanId = isAnnual ? "2023-enterprise-org-seat-annually" : "2023-enterprise-seat-monthly",
                StripeProviderPortalSeatPlanId = null,
                BasePrice = 0,
                SeatPrice = isAnnual ? 72 : 7,
                ProviderPortalSeatPrice = 0,
                AllowSeatAutoscale = true,
                HasAdditionalSeatsOption = true,
                MaxAdditionalSeats = null,
                BaseSeats = 0,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = null,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = isAnnual ? 4 : 0.5M,
                StripeStoragePlanId = isAnnual ? "storage-gb-annually" : "storage-gb-monthly",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 0,
                AllowServiceAccountsAutoscale = true,
                StripeServiceAccountPlanId = isAnnual ? "secrets-manager-service-account-annually" : "secrets-manager-service-account-monthly",
                AdditionalPricePerServiceAccount = isAnnual ? 6 : 0.5M,
                BaseServiceAccount = 200,
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = true,
                StripeSeatPlanId = isAnnual ? "secrets-manager-enterprise-seat-annually" : "secrets-manager-enterprise-seat-monthly",
                HasAdditionalSeatsOption = true,
                BasePrice = 0,
                SeatPrice = isAnnual ? 144 : 13,
                BaseSeats = 0,
                MaxSeats = 0,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = true,
                MaxProjects = 0,
            },
            AutomaticUserConfirmation = false,
        };

        public static LocalPlan CreateEnterprisePlan(bool isAnnual) => new()
        {
            Type = isAnnual ? PlanType.EnterpriseAnnually : PlanType.EnterpriseMonthly,
            ProductTier = ProductTierType.Enterprise,
            Name = isAnnual ? "Enterprise (Annually)" : "Enterprise (Monthly)",
            IsAnnual = isAnnual,
            NameLocalizationKey = "planNameEnterprise",
            DescriptionLocalizationKey = "planDescEnterprise",
            CanBeUsedByBusiness = true,
            TrialPeriodDays = 7,
            HasSelfHost = true,
            HasPolicies = true,
            HasGroups = true,
            HasDirectory = true,
            HasEvents = true,
            HasTotp = true,
            Has2fa = true,
            HasApi = true,
            HasSso = true,
            HasOrganizationDomains = true,
            HasKeyConnector = true,
            HasScim = true,
            HasResetPassword = true,
            UsersGetPremium = true,
            HasCustomPermissions = true,
            HasMyItems = true,
            HasInviteLinks = true,
            UpgradeSortOrder = 4,
            DisplaySortOrder = 4,
            LegacyYear = null,
            Disabled = false,
            PasswordManager = new PasswordManagerPlanFeatures
            {
                StripePlanId = null,
                StripeSeatPlanId = isAnnual ? "2023-enterprise-org-seat-annually" : "2023-enterprise-seat-monthly",
                StripeProviderPortalSeatPlanId = isAnnual ? "password-manager-provider-portal-enterprise-annually-2024" : "password-manager-provider-portal-enterprise-monthly-2024",
                BasePrice = 0,
                SeatPrice = isAnnual ? 72 : 7,
                ProviderPortalSeatPrice = isAnnual ? 72 : 6,
                AllowSeatAutoscale = true,
                HasAdditionalSeatsOption = true,
                MaxAdditionalSeats = null,
                BaseSeats = 0,
                HasPremiumAccessOption = false,
                StripePremiumAccessPlanId = null,
                PremiumAccessOptionPrice = 0,
                MaxSeats = null,
                BaseStorageGb = 5,
                HasAdditionalStorageOption = true,
                AdditionalStoragePricePerGb = isAnnual ? 4 : 0.5M,
                StripeStoragePlanId = isAnnual ? "storage-gb-annually" : "storage-gb-monthly",
                MaxAdditionalStorage = null,
                MaxCollections = null,
            },
            SecretsManager = new SecretsManagerPlanFeatures
            {
                MaxServiceAccounts = 0,
                AllowServiceAccountsAutoscale = true,
                StripeServiceAccountPlanId = isAnnual ? "secrets-manager-service-account-2024-annually" : "secrets-manager-service-account-2024-monthly",
                AdditionalPricePerServiceAccount = isAnnual ? 12 : 1,
                BaseServiceAccount = 50,
                MaxAdditionalServiceAccount = null,
                HasAdditionalServiceAccountOption = true,
                StripeSeatPlanId = isAnnual ? "secrets-manager-enterprise-seat-annually" : "secrets-manager-enterprise-seat-monthly",
                HasAdditionalSeatsOption = true,
                BasePrice = 0,
                SeatPrice = isAnnual ? 144 : 13,
                BaseSeats = 0,
                MaxSeats = 0,
                MaxAdditionalSeats = null,
                AllowSeatAutoscale = true,
                MaxProjects = 0,
            },
            AutomaticUserConfirmation = false,
        };
    }
}
