#!/usr/bin/env bash

test_env() {
  if [ ! -f ./dev/.env ]; then
    echo "Creating ./dev/.env with default key-values"
    echo "COMPOSE_PROJECT_NAME=bitwarden_server" > ./dev/.env
    echo "MSSQL_SA_PASSWORD=d3vP@ssw0rd" >> ./dev/.env
  else
    echo "Found ./dev/.env"
    copy_mssql_var
  fi
}

copy_mssql_var() {
  if grep -q "MSSQL_SA_PASSWORD" ./dev/.env; then
    echo "MSSQL_SA_PASSWORD already exists in ./dev/.env"
  else
    echo "Copying MSSQL_PASSWORD to MSSQL_SA_PASSWORD"
    DB_PASSWORD=$(grep '^MSSQL_PASSWORD=' ./dev/.env)
    echo "${DB_PASSWORD/MSSQL_PASSWORD/MSSQL_SA_PASSWORD}" >> ./dev/.env
    mv ./dev/.env.tmp ./dev/.env
  fi
}

test_env
