<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Subscriptions.User.Test" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.csproj" />
    <ProjectReference Include="..\ExceptionHandling\ExceptionHandling.csproj" />
    <ProjectReference Include="..\Invoicing\Invoicing.csproj" />
  </ItemGroup>

</Project>
