//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bit.Core.Resources.ErrorMessages_en", typeof(ErrorMessages_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ERR001 {
            get {
                return ResourceManager.GetString("ERR001", resourceCulture);
            }
        }
        
        internal static string ERR002 {
            get {
                return ResourceManager.GetString("ERR002", resourceCulture);
            }
        }
        
        internal static string ERR003 {
            get {
                return ResourceManager.GetString("ERR003", resourceCulture);
            }
        }
        
        internal static string ERR000 {
            get {
                return ResourceManager.GetString("ERR000", resourceCulture);
            }
        }
        
        internal static string ERR004 {
            get {
                return ResourceManager.GetString("ERR004", resourceCulture);
            }
        }
        
        internal static string ERR005 {
            get {
                return ResourceManager.GetString("ERR005", resourceCulture);
            }
        }
        
        internal static string ERR006 {
            get {
                return ResourceManager.GetString("ERR006", resourceCulture);
            }
        }
        
        internal static string ERR500 {
            get {
                return ResourceManager.GetString("ERR500", resourceCulture);
            }
        }
        
        internal static string ERR007 {
            get {
                return ResourceManager.GetString("ERR007", resourceCulture);
            }
        }
    }
}
