using Bit.Core.AdminConsole.Utilities.v2;

namespace Bit.Core.AdminConsole.OrganizationFeatures.OrganizationUsers;

public record InvalidTokenError() : BadRequestError("Invalid token.");
public record OrganizationAlreadyEnabledError() : BadRequestError("Organization is already enabled.");
public record OrganizationNotPendingError() : BadRequestError("Organization is not on a Pending status.");
public record OrganizationHasKeysError() : BadRequestError("Organization already has encryption keys.");
public record EmailMismatchError() : BadRequestError("User email does not match invite.");
public record FreeOrgAdminLimitError() : BadRequestError("You can only be an admin of 1 free organization vault.");
public record UserFreeOrgAdminLimitError() : BadRequestError("User can only be an admin of 1 free organization vault.");
public record SingleOrgPolicyViolationError() : BadRequestError("You cannot join this organization vault because you are a member of another organization which forbids it.");
public record TwoFactorRequiredError() : BadRequestError("You cannot join this organization vault until you enable two-step login on your user account.");
public record OrganizationUserNotFoundError() : NotFoundError("User invalid.");
public record OrganizationNotFoundError() : NotFoundError("Organization invalid.");
public record OrganizationMismatchError() : BadRequestError("User does not belong to this organization.");
public record PremiumLicenseError() : BadRequestError("Premium licenses cannot be applied to an organization vault. Upload this license from your personal account Settings page.");
public record LicenseAlreadyInUseError() : BadRequestError("License is already in use by another organization vault.");
public record LeaveOrgSsoBlockedError() : BadRequestError("Your organization single sign-on settings prevent you from leaving.");
public record LeaveOrgClaimedAccountError() : BadRequestError("You can't leave this organization vault because your account is claimed. Contact your admin for more information.");
public record CannotDeleteClaimedAccountError() : BadRequestError("You cannot delete accounts owned by an organization. Contact your admin for additional details.");
public record CannotPurgeClaimedAccountError() : BadRequestError("You cannot purge accounts owned by an organization. Contact your admin for additional details.");
public record FailedToRemoveOrganizationFromProviderError() : BadRequestError("Failed to remove organization vault. Please contact support.");
public record InvitationAlreadyAcceptedError() : BadRequestError("Invitation already accepted. You will receive an email when your organization membership is confirmed.");
public record AlreadyPartOfOrganizationError() : BadRequestError("You are already part of this organization.");
public record UserNotFoundInOrganizationError() : BadRequestError("User not found within organization.");
public record AlreadyAcceptedError() : BadRequestError("Already accepted.");
public record ConfirmUserNotValidError() : BadRequestError("User not valid.");
public record PasswordResetEnrollmentNotAllowedError() : BadRequestError("Organization does not allow password reset enrollment.");
public record PasswordResetPolicyNotEnabledError() : BadRequestError("Organization does not have the password reset policy enabled.");
public record CannotDeleteOrganizationWithKeyConnectorError() : BadRequestError("You cannot delete an organization vault that is using Key Connector.");
public record SecretsManagerMspUnsupportedError() : BadRequestError("Secrets Manager is unsupported because your organization has a Managed Service Provider.");
public record NoPasswordManagerSeatsError() : BadRequestError("You do not have any Password Manager seats!");
public record CannotSubtractPasswordManagerSeatsError() : BadRequestError("You can't subtract Password Manager seats!");
public record PlanDoesNotAllowAdditionalStorageError() : BadRequestError("Plan does not allow additional storage.");
public record CannotSubtractStorageError() : BadRequestError("You can't subtract storage!");
public record PlanDoesNotAllowPremiumAccessAddonError() : BadRequestError("This plan does not allow you to buy the premium access addon.");
public record PlanDoesNotAllowAdditionalUsersError() : BadRequestError("Plan does not allow additional users.");
public record PlanMaxAdditionalUsersExceededError(int MaxSeats) : BadRequestError($"Selected plan allows a maximum of {MaxSeats} additional users.");
public record InvalidSecretsManagerPlanError() : BadRequestError("Invalid Secrets Manager plan selected.");
public record NoSecretsManagerSeatsError() : BadRequestError("You do not have any Secrets Manager seats!");
public record PlanDoesNotAllowAdditionalMachineAccountsError() : BadRequestError("Plan does not allow additional Machine Accounts.");
public record SecretsManagerSeatsMustNotExceedPasswordManagerSeatsError() : BadRequestError("You cannot have more Secrets Manager seats than Password Manager seats.");
public record CannotSubtractMachineAccountsError() : BadRequestError("You can't subtract Machine Accounts!");
public record PlanNullError(string ProductType) : BadRequestError($"{ProductType} Plan was null.");
public record PlanNotFoundError(string ProductType) : BadRequestError($"{ProductType} Plan not found.");
public record CannotSubtractProductSeatsError(string ProductType) : BadRequestError($"You can't subtract {ProductType} seats!");
public record TrialLengthOutOfRangeError() : BadRequestError("Trial length must be between 0 and 30 days.");
