#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to your Bitwarden server
  https://bitwarden.com

Complete documentation:
  https://help.bitwarden.com/hosting/

Configuration:
  Configuration changes can be made in /root/bwdata/config.yml and
  /root/bwdata/env/global.override.env

Common commands:
  /root/bitwarden.sh stop
  /root/bitwarden.sh restart
  /root/bitwarden.sh rebuild

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
