IF EXISTS (
    SELECT *
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE COLUMN_NAME = 'Emails' AND
        DATA_TYPE = 'NVARCHAR (1024)' AND
        TABLE_NAME = 'Send')
BEGIN
    ALTER TABLE [dbo].[Send]
    ALTER COLUMN [Emails] NVARCHAR (4000) NULL
END
GO
