#!/bin/bash

# Scripts in this directory will be executed by cloud-init on the first boot of droplets
# created from your image.  Things like generating passwords, configuration requiring IP address
# or other items that will be unique to each instance should be done in scripts here.

#
# Setup Bitwarden Installer
# ref: https://help.bitwarden.com/article/install-on-premise/
#

curl -s -o docker-compose.yml https://raw.githubusercontent.com/bitwarden/server/master/docker/docker-compose.yml
curl -s -o global.env https://raw.githubusercontent.com/bitwarden/server/master/docker/global.env.example
