#!/bin/bash

# Scripts in this directory will be executed by cloud-init on the first boot of droplets
# created from your image.  Things like generating passwords, configuration requiring IP address
# or other items that will be unique to each instance should be done in scripts here.

#
# Setup Bitwarden Installer
# ref: https://help.bitwarden.com/article/install-on-premise/
#

docker pull bitwarden/setup

curl -s -o /root/bitwarden.sh \
    https://raw.githubusercontent.com/bitwarden/server/master/scripts/bitwarden.sh

chmod +x /root/bitwarden.sh
