namespace Bit.Core.Enums;

public enum GlobalEquivalentDomainsType : byte
{
    Google = 0,
    Apple = 1,
    Ameritrade = 2, // deprecated
    BoA = 3, // deprecated
    Sprint = 4, // deprecated
    WellsFargo = 5, // deprecated
    Merrill = 6,
    Citi = 7, // deprecated
    Cnet = 8, // deprecated
    Gap = 9, // deprecated
    Microsoft = 10,
    United = 11, // deprecated
    Yahoo = 12, // deprecated
    Zonelabs = 13, // deprecated
    PayPal = 14,
    Avon = 15, // deprecated
    Diapers = 16, // deprecated
    Contacts = 17, // deprecated
    Amazon = 18,
    Cox = 19, // deprecated
    Norton = 20, // deprecated
    Verizon = 21, // deprecated
    Buy = 22, // deprecated
    Sirius = 23, // deprecated
    Ea = 24, // deprecated
    Basecamp = 25, // deprecated
    Steam = 26, // deprecated
    Chart = 27, // deprecated
    Gotomeeting = 28, // deprecated
    Gogo = 29, // deprecated
    Oracle = 30, // deprecated
    Discover = 31, // deprecated
    Dcu = 32, // deprecated
    Healthcare = 33, // deprecated
    Pepco = 34, // deprecated
    Century21 = 35, // deprecated
    Comcast = 36,
    Cricket = 37, // deprecated
    Mtb = 38, // deprecated
    Dropbox = 39, // deprecated
    Snapfish = 40, // deprecated
    Alibaba = 41,
    Playstation = 42, // deprecated
    Mercado = 43, // deprecated
    Zendesk = 44, // deprecated
    Autodesk = 45,
    RailNation = 46, // deprecated
    Wpcu = 47, // deprecated
    Mathletics = 48, // deprecated
    Discountbank = 49, // deprecated
    Mi = 50, // deprecated
    Facebook = 51,
    Postepay = 52, // deprecated
    Skysports = 53, // deprecated
    Disney = 54,
    Pokemon = 55, // deprecated
    Uv = 56, // deprecated
    Yahavo = 57, // deprecated
    Mdsol = 58, // deprecated
    Sears = 59, // deprecated
    Xiami = 60, // deprecated
    Belkin = 61, // deprecated
    Turbotax = 62,
    Shopify = 63, // deprecated
    Ebay = 64,
    Techdata = 65, // deprecated
    Schwab = 66, // deprecated
    Mozilla = 67, // deprecated
    Tesla = 68, // deprecated
    MorganStanley = 69,
    TaxAct = 70, // deprecated
    Wikimedia = 71, // deprecated
    Airbnb = 72,
    Eventbrite = 73, // deprecated
    StackExchange = 74,
    Docusign = 75,
    Envato = 76, // deprecated
    X10Hosting = 77, // deprecated
    Cisco = 78, // deprecated
    CedarFair = 79, // deprecated
    Ubiquiti = 80,
    Discord = 81, // deprecated
    Netcup = 82, // deprecated
    Yandex = 83,
    Sony = 84, // deprecated
    Proton = 85,
    Ubisoft = 86, // deprecated
    TransferWise = 87, // deprecated
    TakeawayEU = 88, // deprecated
    Atlassian = 89,
    Pinterest = 90, // deprecated
    Twitter = 91
}
