CREATE VIEW [dbo].[OrganizationView]
AS
SELECT
    O.[Id],
    O.[Identifier],
    O.[Name],
    O.[BusinessName],
    O.[BusinessAddress1],
    O.[BusinessAddress2],
    O.[BusinessAddress3],
    O.[BusinessCountry],
    O.[BusinessTaxNumber],
    O.[BillingEmail],
    O.[UsePolicies],
    O.[UseSso],
    O.[UseGroups],
    O.[UseDirectory],
    O.[UseEvents],
    O.[Use2fA],
    O.[UseApi],
    O.[UseResetPassword],
    O.[SelfHost],
    O.[Gateway],
    O.[GatewayCustomerId],
    O.[GatewaySubscriptionId],
    O.[ReferenceData],
    O.[Enabled],
    O.[LicenseKey],
    O.[ApiKey],
    O.[PublicKey],
    O.[PrivateKey],
    O.[TwoFactorProviders],
    O.[ExpirationDate],
    O.[CreationDate],
    O.[RevisionDate],
    O.[OwnersNotifiedOfAutoscaling],
    O.[UseKeyConnector],
    ISNULL(OPM.[MaxAutoScaleSeats], O.[MaxAutoscaleSeats]) As MaxAutoScaleSeats,
    ISNULL(OPM.[UsersGetPremium], O.[UsersGetPremium]) As UsersGetPremium,
    ISNULL(OPM.[Storage], O.[Storage]) As Storage,
    ISNULL(OPM.[MaxStorageGb], O.[MaxStorageGb]) As MaxStorageGb,
    ISNULL(OPM.[UseTotp], O.[UseTotp]) As UseTotp,
    ISNULL(OPM.[Plan], O.[Plan]) As [Plan],
    ISNULL(OPM.[PlanType], O.[PlanType]) As PlanType,
    ISNULL(OPM.[Seats], O.[Seats]) As Seats,
    ISNULL(OPM.[MaxCollections], O.[MaxCollections]) As MaxCollections
FROM
    [dbo].[Organization] O
    LEFT JOIN OrganizationPasswordManager OPM on OPM.OrganizationId = O.Id
GO