CREATE VIEW [dbo].[SubscriptionDiscountView]
AS
SELECT
    [Id],
    [StripeCouponId],
    [StripeProductIds],
    [PercentOff],
    [AmountOff],
    [Currency],
    [Duration],
    [DurationInMonths],
    [Name],
    [StartDate],
    [EndDate],
    [AudienceType],
    [CreationDate],
    [RevisionDate]
FROM
    [dbo].[SubscriptionDiscount]
