CREATE TABLE [dbo].[PlanTypeGroup](
	[Id]                            [INT]               IDENTITY(1,1) NOT NULL,
	[Name]                          [NVARCHAR](50)      NULL,
	[Description]                   [NVARCHAR](max)     NULL,
	[CanBeUsedByBusiness]           [BIT]               NOT NULL,
	[BaseSeats]                     [INT]               NOT NULL,
	[BaseStorageGb]                 [INT]               NOT NULL,
	[MaxCollections]                [INT]               NULL,
	[HasAdditionalSeatsOption]      [BIT]               NOT NULL,
	[HasAdditionalStorageOption]    [BIT]               NOT NULL,
	[HasPremiumAccessAddon]         [BIT]               NOT NULL,
	[TrialPeriodDays]               [INT]               NOT NULL,
	[HasSelfHost]                   [BIT]               NOT NULL,
	[HasPolicies]                   [BIT]               NOT NULL,
	[HasGroups]                     [BIT]               NOT NULL,
	[HasDirectory]                  [BIT]               NOT NULL,
	[HasEvents]                     [BIT]               NOT NULL,
	[HasTotp]                       [BIT]               NOT NULL,
	[Has2fa]                        [BIT]               NOT NULL,
	[HasApi]                        [BIT]               NOT NULL,
	[UsersGetPremium]               [BIT]               NOT NULL,
	[HasSso]                        [bit]               NOT NULL,
	[SortOrder]                     [INT]               NOT NULL,
	[IsLegacy]                      [BIT]               NOT NULL
    CONSTRAINT [PK_PlanTypeGroup] PRIMARY KEY CLUSTERED ([Id] ASC)
);
