namespace Bit.Core.Auth.UserFeatures.DeviceReadActiveWithPendingAuthRequestsByUserId;

public class DeviceReadActiveWithPendingAuthRequestsByUserIdQuery : IDeviceReadActiveWithPendingAuthRequestsByUserIdQuery
{

}
