#!/bin/bash
#
# Scripts in this directory are run during the build process.
# each script will be uploaded to /tmp on your build droplet, 
# given execute permissions and run.  The cleanup process will
# remove the scripts from your build system after they have run
# if you use the build_image task.
#

#
# Install Docker Compose
# ref: https://docs.docker.com/compose/install/
#

curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` \
    -o /usr/local/bin/docker-compose

chmod +x /usr/local/bin/docker-compose
