<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <RootNamespace>Migrator.Test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="[18.7.0]" />
    <PackageReference Include="xunit.v3" Version="[3.2.1]" />
    <PackageReference Include="xunit.runner.visualstudio" Version="[3.1.5]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\util\Migrator\Migrator.csproj" />
  </ItemGroup>

</Project>
