using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Bit.HttpExtensions.Generator;

/// <summary>
/// Emits the map from validation paths to the codes they should be reported under, for models that must resolve
/// without reflecting over themselves.
/// </summary>
/// <remarks>
/// Emits no validation logic. The framework decides whether a model is valid; this only recovers what its
/// attributes said, because a validation result records a message and discards the constraint that produced it.
/// </remarks>
[Generator]
public sealed class ValidationCodeMapGenerator : IIncrementalGenerator
{
    private const int MaxDepth = 6;

    private static readonly DiagnosticDescriptor Ambiguous = new(
        id: "BWVAL001",
        title: "Validation codes cannot be told apart",
        messageFormat:
            "Property '{0}' carries more than one constraint whose wording cannot be reconstructed, so a failure "
            + "on it cannot be attributed to one of them. Give all but one an ErrorMessage, or reduce it to a "
            + "single constraint.",
        category: "Validation",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description:
            "Failures on this property will be reported without a code rather than with a guessed one.");

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var marked = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Bit.HttpExtensions.GenerateValidationCodesAttribute",
                predicate: static (_, _) => true,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Collect();

        var validatable = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Microsoft.Extensions.Validation.ValidatableTypeAttribute",
                predicate: static (_, _) => true,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Collect();

        context.RegisterSourceOutput(marked.Combine(validatable), static (spc, pair) => Emit(spc, pair.Left, pair.Right));
    }

    private static void Emit(
        SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol> marked,
        ImmutableArray<INamedTypeSymbol> validatable)
    {
        var roots = marked
            .Concat(validatable)
            .Distinct(SymbolEqualityComparer.Default)
            .OfType<INamedTypeSymbol>()
            .OrderBy(static type => type.ToDisplayString(), StringComparer.Ordinal)
            .ToList();

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Bit.HttpExtensions.Generated;");
        source.AppendLine();
        source.AppendLine("internal static class ValidationCodeRegistrations");
        source.AppendLine("{");
        source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        source.AppendLine("    internal static void Register()");
        source.AppendLine("    {");

        var wrote = false;
        foreach (var root in roots)
        {
            var entries = new List<Entry>();
            Walk(root, string.Empty, string.Empty, new List<INamedTypeSymbol> { root }, entries, 0, context);

            if (entries.Count == 0)
            {
                continue;
            }

            wrote = true;
            AppendRegistration(source, root, entries);
        }

        if (!wrote)
        {
            source.AppendLine("        // No marked request models in this assembly.");
        }

        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource("ValidationCodeRegistrations.g.cs", source.ToString());
    }

    private static void AppendRegistration(StringBuilder source, INamedTypeSymbol root, List<Entry> entries)
    {
        source.AppendLine("        global::Bit.HttpExtensions.ValidationCodeMap.Register(");
        source.AppendLine($"            typeof({root.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}),");
        source.AppendLine("            new global::System.Collections.Generic.KeyValuePair<string, global::Bit.HttpExtensions.ValidationCodeEntry>[]");
        source.AppendLine("            {");

        foreach (var entry in entries)
        {
            source.AppendLine($"                new({AttributeTranslator.Quote(entry.Path)}, new global::Bit.HttpExtensions.ValidationCodeEntry(");
            source.AppendLine($"                    {AttributeTranslator.Quote(entry.WirePath)},");
            source.AppendLine($"                    {AttributeTranslator.Quote(entry.DisplayName)},");
            source.AppendLine("                    new global::Bit.HttpExtensions.ValidationCodeCandidate[]");
            source.AppendLine("                    {");

            // A property carrying one constraint cannot be ambiguous, so it needs no wording to be told apart by.
            var ambiguous = entry.Translations.Count > 1;
            foreach (var translation in entry.Translations)
            {
                var message = ambiguous && translation.Construction is not null
                    ? $"static name => {translation.Construction}.FormatErrorMessage(name)"
                    : "null";
                source.Append($"                        new({AttributeTranslator.Quote(translation.Code)}, {message}");
                source.Append(Parameters(translation));
                source.AppendLine("),");
            }

            source.AppendLine("                    })),");
        }

        source.AppendLine("            });");
    }

    private static string Parameters(AttributeTranslation translation)
    {
        if (translation.Parameters.Count == 0)
        {
            return string.Empty;
        }

        var parts = translation.Parameters.Select(p =>
            $"new({AttributeTranslator.Quote(p.Key)}, {p.Value})");
        return $", new global::System.Collections.Generic.KeyValuePair<string, object?>[] {{ {string.Join(", ", parts)} }}";
    }

    private sealed record Entry(
        string Path, string WirePath, string DisplayName, List<AttributeTranslation> Translations);

    /// <summary>
    /// Walks the model graph, recording every property that carries a constraint.
    /// </summary>
    /// <remarks>
    /// Paths mirror what validation produces: dotted for nesting, <c>[]</c> for a collection element. The wire
    /// path is built alongside so the document can name what the client actually sent.
    /// </remarks>
    private static void Walk(
        INamedTypeSymbol type,
        string prefix,
        string wirePrefix,
        List<INamedTypeSymbol> visiting,
        List<Entry> entries,
        int depth,
        SourceProductionContext context)
    {
        if (depth > MaxDepth)
        {
            return;
        }

        foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.DeclaredAccessibility != Accessibility.Public || property.IsStatic ||
                property.GetMethod is null || property.IsIndexer)
            {
                continue;
            }

            var path = prefix + property.Name;
            var wirePath = wirePrefix + WireName(property);

            var translations = new List<AttributeTranslation>();
            foreach (var attribute in property.GetAttributes())
            {
                if (AttributeTranslator.IsValidationAttribute(attribute) &&
                    AttributeTranslator.Translate(attribute) is { } translation)
                {
                    translations.Add(translation);
                }
            }

            if (translations.Count > 0)
            {
                // Exactly one candidate may be identified by elimination; two would make the choice a guess.
                if (translations.Count > 1 && translations.Count(t => t.Construction is null) > 1)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Ambiguous, property.Locations.FirstOrDefault(), path));
                }
                else
                {
                    entries.Add(new Entry(path, wirePath, DisplayName(property), translations));
                }
            }

            var (nested, isCollection) = Unwrap(property.Type);
            if (nested is null || AlreadyVisiting(visiting, nested))
            {
                continue;
            }

            var separator = isCollection ? "[]." : ".";
            visiting.Add(nested);
            Walk(nested, path + separator, wirePath + separator, visiting, entries, depth + 1, context);
            visiting.RemoveAt(visiting.Count - 1);
        }
    }

    private static bool AlreadyVisiting(List<INamedTypeSymbol> visiting, INamedTypeSymbol candidate)
    {
        foreach (var seen in visiting)
        {
            if (SymbolEqualityComparer.Default.Equals(seen, candidate))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// The model behind a property type: the element for a collection, the underlying type for a nullable, and
    /// null for anything that is a value rather than a model.
    /// </summary>
    private static (INamedTypeSymbol? Type, bool IsCollection) Unwrap(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array)
        {
            return (Walkable(array.ElementType), true);
        }

        if (type is not INamedTypeSymbol named)
        {
            return (null, false);
        }

        if (named.IsGenericType && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            return (Walkable(named.TypeArguments[0]), false);
        }

        if (named.SpecialType != SpecialType.System_String)
        {
            foreach (var iface in named.AllInterfaces.Concat(new[] { named }))
            {
                if (iface.IsGenericType &&
                    iface.ConstructedFrom.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
                {
                    return (Walkable(iface.TypeArguments[0]), true);
                }
            }
        }

        return (Walkable(named), false);
    }

    /// <summary>A type worth descending into: one of ours, with properties that could carry constraints.</summary>
    private static INamedTypeSymbol? Walkable(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol named ||
            named.TypeKind is not (TypeKind.Class or TypeKind.Struct) ||
            named.SpecialType != SpecialType.None ||
            named.IsGenericType)
        {
            return null;
        }

        var containing = named.ContainingNamespace?.ToDisplayString() ?? string.Empty;
        if (containing.Length == 0 ||
            containing == "System" || containing.StartsWith("System.", StringComparison.Ordinal) ||
            containing == "Microsoft" || containing.StartsWith("Microsoft.", StringComparison.Ordinal))
        {
            return null;
        }

        return named;
    }

    /// <summary>The name the client sent: the JSON name when renamed, otherwise the camel-cased property.</summary>
    private static string WireName(IPropertySymbol property)
    {
        foreach (var attribute in property.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonPropertyNameAttribute" &&
                attribute.ConstructorArguments.Length > 0 &&
                attribute.ConstructorArguments[0].Value is string name)
            {
                return name;
            }
        }

        var clr = property.Name;
        return clr.Length > 0 && char.IsUpper(clr[0]) ? char.ToLowerInvariant(clr[0]) + clr.Substring(1) : clr;
    }

    /// <summary>The name the framework puts in its messages.</summary>
    private static string DisplayName(IPropertySymbol property)
    {
        foreach (var attribute in property.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != "System.ComponentModel.DataAnnotations.DisplayAttribute")
            {
                continue;
            }

            foreach (var named in attribute.NamedArguments)
            {
                if (named.Key == "Name" && named.Value.Value is string display)
                {
                    return display;
                }
            }
        }

        return property.Name;
    }
}
