name: SDLC / Enforce PR labels
run-name: Enforce labels for PR ${{ github.event.pull_request.number }}

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize]

permissions: {}

jobs:
  enforce-label:
    name: Enforce Label
    uses: bitwarden/gh-actions/.github/workflows/_enforce-pr-labels-sdlc.yml@main
    permissions:
      pull-requests: read