name: Publish
run-name: Publish ${{ inputs.dry_run && '(Dry Run)' || '' }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (default: latest release)'
        required: true
        type: string
        default: latest
      branch:
        description: "Branch to publish from"
        required: true
        type: choice
        options:
          - rc
          - hotfix-rc
        default: rc
      dry_run:
        description: "Dry Run"
        type: boolean
        default: false

env:
  _AZ_REGISTRY: "bitwardenprod.azurecr.io"
  _GHCR_REGISTRY: "ghcr.io/bitwarden"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    permissions:
      deployments: write
    outputs:
      deployment-id: ${{ steps.deployment.outputs.deployment_id }}
      release-version: ${{ steps.version-output.outputs.version }}
    steps:
      - name: Version output
        id: version-output
        env:
          INPUT_VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${INPUT_VERSION}" == "latest" || "${INPUT_VERSION}" == "" ]]; then
            VERSION=$(gh api repos/bitwarden/server/releases/latest --jq '.tag_name | ltrimstr("v")')
            echo "Latest Released Version: $VERSION"
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          else
            VERSION="${INPUT_VERSION#v}"
            echo "Release Version: ${VERSION}"
            echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create GitHub deployment
        if: ${{ !inputs.dry_run }}
        uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1 # v2.0.7
        id: deployment
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          initial-status: 'in_progress'
          environment: 'production'
          description: 'Deployment ${{ steps.version-output.outputs.release-version }} from branch ${{ github.ref_name }}'
          task: release

  publish-docker:
    name: Publish Docker images
    runs-on: ubuntu-22.04
    needs: setup
    permissions:
      contents: read
      id-token: write
      packages: write
    env:
      _RELEASE_VERSION: ${{ needs.setup.outputs.release-version }}
      _BRANCH_NAME: ${{ inputs.branch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - project_name: Admin
          - project_name: Api
          - project_name: Attachments
          - project_name: Billing
          - project_name: Events
          - project_name: EventsProcessor
          - project_name: Icons
          - project_name: Identity
          - project_name: MsSql
          - project_name: MsSqlMigratorUtility
          - project_name: Nginx
          - project_name: Notifications
          - project_name: Scim
          - project_name: Setup
          - project_name: Sso
    steps:
      - name: Print environment
        run: |
          whoami
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event: $GITHUB_EVENT"
          echo "Dry Run: ${{ inputs.dry_run }}"

      - name: Set up project name
        id: setup
        run: |
          PROJECT_NAME=$(echo "${{ matrix.project_name }}" | awk '{print tolower($0)}')
          echo "Matrix name: ${{ matrix.project_name }}"
          echo "PROJECT_NAME: $PROJECT_NAME"
          echo "project_name=$PROJECT_NAME" >> "$GITHUB_OUTPUT"

      ########## GHCR ##########
      - name: Log in to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push version image
        env:
          PROJECT_NAME: ${{ steps.setup.outputs.project_name }}
        run: |
          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            skopeo copy --all \
              "docker://$_GHCR_REGISTRY/$PROJECT_NAME:$_BRANCH_NAME" \
              "docker://$_GHCR_REGISTRY/$PROJECT_NAME:dryrun"
          else
            skopeo copy --all \
              "docker://$_GHCR_REGISTRY/$PROJECT_NAME:$_BRANCH_NAME" \
              "docker://$_GHCR_REGISTRY/$PROJECT_NAME:$_RELEASE_VERSION"
          fi

      - name: Log out from GHCR
        run: docker logout ghcr.io

      ########## ACR ##########
      - name: Log in to Azure
        uses: bitwarden/gh-actions/azure-login@main
        with:
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          client_id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Log in to Azure ACR
        run: az acr login -n "$_AZ_REGISTRY" --only-show-errors

      - name: Push version and latest image
        env:
          PROJECT_NAME: ${{ steps.setup.outputs.project_name }}
        run: |
          if [[ "${{ inputs.dry_run }}" == "true" ]]; then
            skopeo copy --all \
              "docker://$_AZ_REGISTRY/$PROJECT_NAME:latest" \
              "docker://$_AZ_REGISTRY/$PROJECT_NAME:dryrun"
          else
            skopeo copy --all \
              "docker://$_AZ_REGISTRY/$PROJECT_NAME:$_BRANCH_NAME" \
              "docker://$_AZ_REGISTRY/$PROJECT_NAME:$_RELEASE_VERSION"
            skopeo copy --all \
              "docker://$_AZ_REGISTRY/$PROJECT_NAME:$_BRANCH_NAME" \
              "docker://$_AZ_REGISTRY/$PROJECT_NAME:latest"
          fi

      - name: Log out from Azure
        uses: bitwarden/gh-actions/azure-logout@main

  update-deployment:
    name: Update Deployment Status
    runs-on: ubuntu-22.04
    needs:
      - setup
      - publish-docker
    permissions:
      deployments: write
    if: ${{ always() && !inputs.dry_run }}
    steps:
      - name: Check if any job failed
        if: contains(needs.*.result, 'failure')
        run: exit 1

      - name: Update deployment status to Success
        if: success()
        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          state: 'success'
          deployment-id: ${{ needs.setup.outputs.deployment-id }}

      - name: Update deployment status to Failure
        if: failure()
        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          state: 'failure'
          deployment-id: ${{ needs.setup.outputs.deployment-id }}
